### ISSUE TITLE
Make all test properties dynamic, and support much easier ways to set them

### ISSUE THREAD

**Issue by svanoort** [svanoort/pyresttest#101]
As a user of PyRestTest, I'd like to be able to set all test properties dynamically so I don't repeat myself.  It would also be nice to make use of generators and variable simpler, and support raw values (not just strings for templates). 

Nice to have: extensible templating, using something such as Jinja2. 

**Suggested syntax:**
```yaml
- value: {variable: 'myVariableName'}  # Raw value of variable is used
- value2: {file: 'myFile'}  # File is a path
- standard: {template: 'template $value in string'}  # old form
- generator_property: {generator: 'myGeneratorName'}  # Uses name of generator to store value
- special_text: {jinja2: 'value_template_whee'}  # Custom template text
```
**TOOD: look if there are better/shorter syntaxes for this (I.E. look at ansible)**

**Challenges:**
* what if we have multiple items?  Like, a template *and* a file value?  Which is used?
  - This might be the biggest problem!  Also the syntax is slightly clunky with a dictionary type
* nesting: template + file + jinja?  (should be supported, but need test just like Contexts)
* dynamic-to-dynamic references: is it evaluated up-front when first encountered in tests, i.e. define variable dynamically then evaluate, or lazily every time?

**Work Items:**
* Depends on [parsing refactoring](https://github.com/svanoort/pyresttest/issues/75) to be easy to use
* Needs to store the dynamic portion and then replace every getter call with a property?
* Caching of results if not changing?
* Architecture: use properties/proxies fed by the context?

For nice-to-have:
* registry approach to parsing/looking up variable data sources

Example:
* Content module, used for request bodies, etc
