### ISSUE TITLE
Provide extractors to work with raw cookie data

### ISSUE THREAD

**Issue by nitrocode** [svanoort/pyresttest#144]
I'm trying to do the following

1. Run login test to grab the SESSION_ID cookie
2. Run actual test using SESSION_ID cookie

Here is my YAML

```
---
- config:
    - testset: "Testing login..."

# This works
- test:
    - group: "Quickstart"
    - name: "Login"
    - url: "/api/v1/users/process-login"
    - method: "POST"
    - body: 'username=qa@testing.com&password=qa'
    - headers: {'Content-Type': 'application/x-www-form-urlencoded'}

# This does not because it doesn't use the cookie obtained in the previous test
- test:
    - group: "Quickstart"
    - name: "Get data"
    - url: "/api/v1/search"
    - method: "GET"
    - body: 'type=contacts'
    - headers: {'Content-Type': 'application/json'}
```

Is there a way I can write an extractor that will extract the cookie from the first test and push it into the second test?

I got the underlying curl commands to work:

```
loginurl="http://localhost:8888/api/v1/users/process-login"
# create cookie
curl -c mycookie "$loginurl" -d "username=qa@testing.com" -d "password=qa" --referer "$loginurl"
# use cookie
curl -b mycookie "http://localhost:8888/api/v1/search?type=contacts"
```

I could do this all in curl but I'd much rather use your YAML abstraction layer. Any advice on how to make my YAML connect to my API like I was able to using curl's cookie I/O?

**Comment by svanoort** [comment]
Hi, 
Yes, there's a header extractor that *should* be able to pull cookies out and reuse them in tests, example case here: https://github.com/svanoort/pyresttest/issues/70

It's fairly basic, you can use it to pull the cookie headers out and use them as variables for templating, but may serve for your use case.  It won't be able to set multiple cookie headers at the same time though until https://github.com/svanoort/pyresttest/issues/74 is resolve. 

 Does that work? 

Thanks, 
Sam

**Comment by svanoort** [comment]
@nitrocode  ^ reply above

**Comment by nitrocode** [comment]
Thank you for the quick reply @svanoort but I'm having trouble setting up the extractor. I read through your advanced guide but I wasn't able to find any examples that would work for me. I also found #70 and attempted the following to no avail.

```
    ... (from the first test)
    - body: 'username=qa@testing.com&password=qa'
    - headers: {'Content-Type': 'application/x-www-form-urlencoded'}
    - extract_binds: # added this
        - 'SetCookie': { header: 'Set-Cookie'} # added this

# This does not because it doesn't use the cookie obtained in the previous test
- test:
    - group: "Quickstart"
    - name: "Get data"
    - url: "/api/v1/search"
    - method: "GET"
    - body: 'type=contacts'
    #- headers: {'Content-Type': 'application/json'}
    - headers: {'Content-Type': 'application/json', 'Set-Cookie': $SetCookie} #added this but it doesnt use the $SetCookie variable from the 1st test
```

How would I change my YAML file so I can extract `Set-Cookie` and plugin the same into the second test?
