### ISSUE TITLE
[Bug?] POST using x-www-form-urlencoded causes issue with templating

### ISSUE THREAD

**Issue by nitrocode** [svanoort/pyresttest#147]
When I use POST, I saw that these 2 lines had different results. Is this a bug?

```
# this works
    - body: 'username=qa@testing.com&password=test'
# this does not
    - body: '{"username": "qa@testing.com", "password": "test"}'
```

I also tried templating with the working line but it did not have the correct results.

```
- config:
    - variable_binds: {'user': 'qa@testing.com', 'pass': 'test'}
- test
    ...
    - body: {template: 'username=$user&password=$pass'}
```

Tried using the following flags but wasn't able to do any further debugging:

` --print-bodies=true --print-headers=true --ssl-insecure --verbose --log=debug`

The only example using [x-www-form-urlencoded](https://github.com/svanoort/pyresttest/blob/fa57dd0dc8e12469d5e93b3af0665f725ac2e3b0/examples/dummyapp-posting-forms.yaml) doesn't use templating. Am I templating poorly?
