### ISSUE TITLE
Disable case sensitivity

### ISSUE THREAD

**Issue by nitrocode** [svanoort/pyresttest#148]
Noticed that when checking my header for _Application/json_ it did not work until I checked it for _application/json_

```
    - validators:
         - compare: {header: 'Content-Type', comparator: 'str_eq', expected: "Application/json"}
    - validators:
         - compare: {header: 'Content-Type', comparator: 'str_eq', expected: "application/json"}
```

Is there a configuration parameter that can disable case sensitivity?
