### ISSUE TITLE
pyresttest speed issue

### ISSUE THREAD

**Issue by nitrocode** [svanoort/pyresttest#152]
We're evaluating using requests instead of pyresttest because we've had issues with speed.

My login.yaml test takes about 24 seconds to run using pyresttest and a more extended test using the requests module, no yaml, and unittest2 takes about 6 seconds. Has another else noticed this too?

I'm speculating but the slow down in pyresttest may be due to the initial processing prior to sending the first curl request. After stepping through the program, with a break point on `curl.perform()` on [line 350](https://github.com/svanoort/pyresttest/blob/master/pyresttest/resttest.py#L350), it took about 4 to 5 seconds to before calling the curl statement. Is there a way to speed this up?

**Comment by svanoort** [comment]
>  may be due to the initial processing prior to sending the first curl request

 **Installing libyaml may speed it up**, because pyyaml can use that for faster parsing of the YAML (possible bottleneck).

Yes, there is a fixed overhead to parsing and validating the test structure (it shouldn't be this much though), but it's a one-time cost and *should not* be that long unless your tests are extremely large or complex.

I would need to be able to replicate this and do some experimentation to see where the overheads are. 
Can you provide sample YAML and which version of Python, PyRestTest (from source or stable release from PIP), and what OS you're running? 

In general, once the initial parsing & configuration is done, the actual requests *should* be fairly fast, because [PyCurl's native code is considerably faster than requests](http://stackoverflow.com/a/32899936/95122) (link is to a benchmark I did).  There's some overhead in configuring and analyzing each request/response pair, of course. 

The benchmark methods are fairly optimized: there's a test for performance in there, which has shown that overhead is <0.3 ms per request on a fairly weak system.  I'll have to see if that has regressed. 

The test methods *haven't* been as optimized, because they do some additional processing and there hasn't been a need yet.  The curl handles could be reused (big performance gain), and there's some room for caching of templates (one smaller bottleneck).

**Comment by svanoort** [comment]
@nitrocode  ^

**Comment by nitrocode** [comment]
Hi @svanoort, here is my setup

    python 2.7.11
    pyyaml 3.11
    Windows 7 and CentOS 7

sampletest:

```yaml
---
- config:
    - testset: 'Testing free api'
    - timeout: 60
    - curl_option_SSL_CIPHER_LIST: 'rsa_rc4_128_sha'

- test:
    - group: "Quickstart"
    - name: "Get data"
    - url: '/posts/1'
    - method: 'GET'
    - validators:
         - compare: {jsonpath_mini: 'userId', comparator: 'gt', expected: 0}
```

command:

    python pyresttest/pyresttest/resttest.py http://jsonplaceholder.typicode.com sampletest/jsonplaceholder.yml

This takes about 30 seconds

### Possible slow down

I haven't looked too deeply into this but recently I've been experimenting with [yaml](https://github.com/Animosity/CraftIRC/wiki/Complete-idiot's-introduction-to-yaml) files and pyyaml and noticed that parsing yaml files that use dashes (lists) take a lot longer than without. I also noticed that there seems to be an overhead with iterating over yaml files that have many dashes which is the case of pyrestest. Though, I'm just speculating.

Take for example the [examples/minimap-test.yaml](https://github.com/svanoort/pyresttest/blob/master/examples/miniapp-benchmark.yaml) file and remove all of the dashes and replace the no-value keys with 'true' called minimap-test-no-lists.yaml

```yaml
---
- config:
    testset: "Benchmark tests using test app"

- benchmark: # create entity
    name: "Basic get"
    url: "/api/person/"
    warmup_runs: 7
    'benchmark_runs': '101'
    output_file: 'miniapp-benchmark.csv'
    metrics:
        total_time: 'true'
        total_time: mean
        total_time: median
        size_download: 'true'
        speed_download: median

- benchmark: # create entity
    name: "Get single person"
    url: "/api/person/1/"
    metrics: {speed_upload: median, speed_download: median, redirect_time: mean}
    output_format: json
    output_file: 'miniapp-single.json'
```

Here is the time processed and output of your yaml file

```javascript
Took 30.9998989105 msec to parse minimap-test.yaml
[{'config': [{'testset': 'Benchmark tests using test app'}]},
 {'benchmark': [{'name': 'Basic get'},
   {'url': '/api/person/'},
   {'warmup_runs': 7},
   {'benchmark_runs': '101'},
   {'output_file': 'miniapp-benchmark.csv'},
   {'metrics': ['total_time',
     {'total_time': 'mean'},
     {'total_time': 'median'},
     'size_download',
     {'speed_download': 'median'}]}]},
 {'benchmark': [{'name': 'Get single person'},
   {'url': '/api/person/1/'},
   {'metrics': {'redirect_time': 'mean',
     'speed_download': 'median',
     'speed_upload': 'median'}},
   {'output_format': 'json'},
   {'output_file': 'miniapp-single.json'}]}]
```

Here it is for the same file without the dashes (no lists)

```javascript
Took 20.9999084473 msec to parse minimap-test-no-lists.yml
[{'config': {'testset': 'Benchmark tests using test app'}},
 {'benchmark': {'benchmark_runs': '101',
   'metrics': {'size_download': 'true',
    'speed_download': 'median',
    'total_time': 'median'},
   'name': 'Basic get',
   'output_file': 'miniapp-benchmark.csv',
   'url': '/api/person/',
   'warmup_runs': 7}},
 {'benchmark': {'metrics': {'redirect_time': 'mean',
    'speed_download': 'median',
    'speed_upload': 'median'},
   'name': 'Get single person',
   'output_file': 'miniapp-single.json',
   'output_format': 'json',
   'url': '/api/person/1/'}}]
```

So there is roughly a 50% decrease in time (10 msec) in processing time just by converting the function and from looking at the json differences, the complexity falls a bit once the list of lists are converted into key-value pairs.

Get benchmark's metric's `total_time` using minimap-test.yml

`data[1]['benchmark'][5]['metrics'][2]`

Using minimap-test-no-lists.yml

`data[1]['benchmark']['metrics']['total_time']`
