### ISSUE TITLE
extract_binds with imports

### ISSUE THREAD

**Issue by tentoseven** [svanoort/pyresttest#169]
I'm trying to use a variable extracted from the headers through my tests. My main .yaml file is simply:

```
---
- config:
    - testset: "App tests"

- import: test/auth.yaml
- import: test/items.yaml
```

Both imported files use the same test set, and the lifecycle docs say:

> Parse YAML, reading top-level imports and building TestSets

and also:

> Generate a Context **for each test set**, populated with generators and variables defined in the TestConfig

And:

> Contexts are persistent within a TestSet. Once a variable is set, it can be used in all following tests

But a variable declared in the first import isn't available in the second. I've moved the tests from the second import into the first import and it all works perfectly, so the variable is definitely being set correctly. 

Example from `auth.yaml`:

```
---
- config:
    - testset: "App tests"

- test:
    - group: "Authentication"
    - name: "User successful login"
    - url: "/api/v0.1/auth/"
    - method: "POST"
    - body: '{"username": "xxxx", "password": "xxxx", "pin": xxxx }'
    - headers: {"Content-Type": "application/json"}
    - expected_status: [200]
    - validators:
      - json_schema: {schema: {file: "auth-schema.json"}}
    - extract_binds:
      - "auth_key": {"jsonpath_mini": "token"}
```

And then `items.yaml`:

```
---
- config:
    - testset: "App tests"

- test:
    - group: "Items"
    - name: "User item listing successful"
    - url: "/api/v0.1/items/?limit=10"
    - method: "GET"
    - headers: { template: {"Api-Key": "$auth_key", "Content-Type": "application/json"}}
    - expected_status: [200]
```

Do I need a config section in each imported file? Adding or removing it seems to make no difference to how the tests run.

The item listing call using verbose mode shows:

`Api-Key:$auth_key`
