### ISSUE TITLE
Is there an extension points for "body"?

### ISSUE THREAD

**Issue by norbertkeri** [svanoort/pyresttest#217]
I would like to make writing JSON post bodies a bit more friendly in regards to syntax, eg. pass in a dict as the body, instead of manually JSON serializing it to a string. I was thinking doing something like:

```
- test:
    name: Test creating an organisation unit
    url: organisationUnits
    method: POST
    body:
        json_dict:
            name: "hello"
            shortName: "world"
```

But I couldn't find an extension point for the "body" attribute. Is there one? If not, can you give me some pointers on where would I start implementing it?
