### ISSUE TITLE
Unable to set value of extract binds

### ISSUE THREAD

**Issue by mr-karan** [svanoort/pyresttest#232]
I want to use an access token obtained from a previous Authentication route but I am unable to properly set it. 

`test.yaml` 

```
---
- config:
    - testset: "Basic tests"
- test:
    - name: "Get Auth Token"
    - url: "/o/token/"
    - method: "POST"
    - body: 'grant_type=password&client_id=&client_secret=&password=&username='
    - headers: {'Content-Type': 'application/x-www-form-urlencoded'}
    - expected_status: [200]
    - extract_binds:
        - 'token': {'jsonpath_mini': 'access_token'}

- test:
    - name: "Get details"
    - url: "/api/details"
    - method: "GET"
    - headers: {'Authorization': 'Bearer $token'}
    - expected_status: [200]
```

### Error Message 
```
REQUEST:
GET http://localhost:8000/api/details
HEADERS:
{'Authorization': 'Bearer $token'}
Press ENTER when ready (0):
DEBUG:Initial Test Result, based on expected response code: False
RESPONSE:
{"detail":"Authentication credentials were not provided."}
```

This error message comes when the $token value isn't set i.e. Authentication token isn't provided.

### Equivalent cURL request is 
```
curl -X GET -H "Authorization: Bearer <token value>" -H "Cache-Control: no-cache"  "http://localhost:8000/api/details"
```

Any help is much appreciated
