### ISSUE TITLE
Global variables for import

### ISSUE THREAD

**Issue by j796160836** [svanoort/pyresttest#256]
Hi,  
I also using this awesome framework.  
It does have import yaml test case, but variables are **independent** between child and parent.  
  
```
- import: a.yaml
```

https://github.com/svanoort/pyresttest#import-example

I'm looking for variable sharing between child and parent.  
My case want to define global variables in a file and expose to child

**main.yaml**
```
# Test case entrance
---
- config:
    - testset: "Test case"

- import: a.yaml
- import: b.yaml
- import: c.yaml
```

**a.yaml**
```
# Test set A
---
- config:
    - testset: "Test set A"
    - global_variables: variables.yaml  # Get the global variables from file
- test:
     do stuff
```

**b.yaml**
```
# Test set B
---
- config:
    - testset: "Test set B"
    - global_variables: variables.yaml  # Get the global variables from file
- test:
     # do some stuff
```
**variables.yaml**
```
# Global variables
---
- config:
    - variable_binds: {"foo": "bar"}
```
Is that possible to do this?
