### ISSUE TITLE
How to use generators of type 'fixed_sequence'? 

### ISSUE THREAD

**Issue by kiptoomm** [svanoort/pyresttest#264]
Does anyone have a working example for how to use the 'fixed_sequence' type of generators? In https://github.com/svanoort/pyresttest/blob/master/advanced_guide.md, I can only see an example for the 'number_sequence' type. 

I have defined my config like the following:
```
- config:
    - testset: "Test CRUD Operations"
    - timeout: 100  # Increase timeout from the default 10 seconds
    - headers: {'Content-Type': 'application/vnd.api+json'}
    - variable_binds: {firstname: 'first', lastname: 'last'}
    - generators:
      - 'id': {type: 'number_sequence', start: 2}
      - 'random_name': {type: 'random_text'}
      - 'item_counts': {type: 'fixed_sequence', values: [4, 3, 1, 2, 5]}
```

And now I'm trying to create the buyer entries like so:
```
- benchmark: # create new buyer entries
  - generator_binds: {buyer_id: id, items: item_counts}
  - name: "create buyers"
  - url: {template: "/api/buyer"}
  - warmup_runs: 0
  - method: 'POST'
  - headers: {'Content-Type': 'application/vnd.api+json'}
  - body: {template:
            '{
              "data": {
                "type": "buyer",
                "attributes": {
                  "id": "$buyer_id",
                  "first_name": "$firstname$buyer_id",
                  "last_name": "$lastname$buyer_id",
                  "items_bought": "$items"
                }
              }
            }'
          }
  - benchmark_runs: '5' # create 5 buyers
  - metrics:
    - total_time: total
    - total_time: mean
```

Problem is that my server seems to only receive the first item of the 'items' array, so all values of the 'items_bought' column are set to 4, when it should loop through the entire array and populate each row accordingly. What am I missing?
