### ISSUE TITLE
Exists Extractors failing when value is null

### ISSUE THREAD

**Issue by jeanCarloMachado** [svanoort/pyresttest#28]
The following test fails when the value keys are zero on the result

```
- config:
    - testset: "Finance"
    - generators:  
        - 'ACCESSTOKEN': {type: 'env_variable', variable_name: ACCESSTOKEN}
- test:
    - group: "Revenue"
    - name: "Get Revenue"
    - url: "/rpc/v1/finance.get-revenue.json"
    - method: "POST"
    - expected_status: [200]
    - headers: {template: {"Authorization": "$ACCESSTOKEN"}}
    - validators: 
        - extract_test: {jsonpath_mini: "0.id",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.dueDate",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.account",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.account_name",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.person",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.client_name",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.description",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.portion",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.repeatTimes",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.value",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.creationDate",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.status",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.expired",  test: "exists"}
```

The result:

```
[
    {
        "id":1,
        "dueDate":"2014-12-24",
        "account":4,
        "account_name":"Account 1",
        "person":1,
        "client_name":"Client1",
        "description":"Revenue description Test One",
        "portion":0,
        "repeatTimes":0,
        "value":1000,
        "creationDate":"2014-12-24",
        "status":"-1",
        "expired":"0"
    }
]
```

Portion and repeatTimes fails.
