### ISSUE TITLE
extract_binds usage help is appreciated 

### ISSUE THREAD

**Issue by imangohari1** [svanoort/pyresttest#287]
Hi, 
I'm having the following ReST message: 
```
HTTP/1.1 200 OK
Date: Mon, 06 Aug 2018 15:32:21 GMT
Content-Length: 90
Content-Type: text/plain; charset=utf-8

{"responseCode":0,"responseMsg":"Initiated","userId":4,"stackId":1,"stackResponseCode":0}
```
and I'm trying to use the `extact_binds` to get the value of `stackId`:
```
- test:
   - group: "CMT Test"
   - name: "Stack Creation"
   - url: "XXX"
   - method: 'POST'
   - body: 'XXXX'
   - expected_status: [200]
   - headers: {'Content-Type': 'text/plain'}
   - extract_binds:
       - 'id': {'raw_body': 'stackId'}
   - validators:
       - extract_test: {raw_body: "stackId",  test: "exists"}
       - compare: {raw_body: "stackId", comparator: contains , expected: '$id'}
```
Unfortunately I'm facing the following error:
```
ERROR:Test Failure, failure type: Validator Failed, Reason: Comparison failed, evaluating contains({"responseCode":0,"responseMsg":"Initiated","userId":4,"stackId":26,"stackResponseCode":0}
, $id) returned False
```
any help is appreciated!
