### ISSUE TITLE
Counting elements of base object

### ISSUE THREAD

**Issue by jbroenstrup** [svanoort/pyresttest#304]
I am trying to count the elements in an array that is at the root of an API response. Might look like this:

```json
[
  {"name": "john"},
  {"name": "clarice"}
]
```

The test I wrote uses the following test/comparer:

```yaml
- test:
    - name: "Get all people"
    - url: "/api/people"
    - method: 'GET'
    - expected_status: [200]
    - validators:
        - compare: {jsonpath_mini: " ??? ", comparator: "ge", expected: 2}
```

I tried pretty much all variations of length(.), length("."), length("") etc. pp.

What am I doing wrong here?

**Comment by jbroenstrup** [comment]
I made a mistake. I was using the wrong comparer! Comparer mus be jmespath and the length of the main array can be retrieved like to length('[]').

So complete test definition must be:

```yaml
- test:
    - name: "Get all people"
    - url: "/api/people"
    - method: 'GET'
    - expected_status: [200]
    - validators:
        - compare: {jmespath : "length('[]')", comparator: "ge", expected: 2}
```
