### ISSUE TITLE
There's a way to set a jsonpath_mini extracted data as a variable?

### ISSUE THREAD

**Issue by jeanCarloMachado** [svanoort/pyresttest#41]
```
- config:
    - testset: "Inventory Group"
    - generators:
       - 'ACCESSTOKEN': {type: 'env_variable', variable_name: ACCESSTOKEN}
- test:
    - group: "Group"
    - name: "Post Group"
    - url: "/rpc/v1/inventory.post-group.json"
    - method: "POST"
    - expected_status: [200]
    - body: "name=NewGroup"
    - headers: {template: {"Authorization": "$ACCESSTOKEN"}}
    - validators:
        - compare: {jsonpath_mini: "status",     comparator: "eq",     expected: 1}
- test:
    - group: "Group"
    - name: "Get group"
    - url: "/rpc/v1/inventory.get-group.json"
    - method: "POST"
    - expected_status: [200]
    - headers: {template: {"Authorization": "$ACCESSTOKEN"}}
    - validators:
        - extract_test: {jsonpath_mini: "0.id",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.name",  test: "exists"}
    - variable_binds: {CURRENTID: "0.id"}
- test:
    - group: "Group"
    - name: "Update group"
    - url: "/rpc/v1/inventory.put-group.json"
    - method: "POST"
    - body: {template: "name=NewName&id=$CURRENTID"}
    - expected_status: [200]
    - headers: {template: {"Authorization": "$ACCESSTOKEN"}}
    - validators:
        - compare: {jsonpath_mini: "status",     comparator: "eq",     expected: 1}
```

Given this exemple, there's a way of getting the 0.id and set is as CURRENTID ?
