### ISSUE TITLE
Get last entry of array with json_path_mini

### ISSUE THREAD

**Issue by jeanCarloMachado** [svanoort/pyresttest#42]
I kow it relates with (this)[https://github.com/svanoort/pyresttest/issues/39] generic issue but I need a specific answer.

```
- config:
    - testset: "Inventory Group"
    - generators:
       - 'ACCESSTOKEN': {type: 'env_variable', variable_name: ACCESSTOKEN}
- test:
    - group: "Group"
    - name: "Post Group"
    - url: "/rpc/v1/inventory.post-group.json"
    - method: "POST"
    - expected_status: [200]
    - body: "name=NewGroup"
    - headers: {template: {"Authorization": "$ACCESSTOKEN"}}
    - validators:
        - compare: {jsonpath_mini: "status",     comparator: "eq",     expected: 1}
- test:
    - group: "Group"
    - name: "Get group"
    - url: "/rpc/v1/inventory.get-group.json"
    - method: "POST"
    - expected_status: [200]
    - headers: {template: {"Authorization": "$ACCESSTOKEN"}}
    - validators:
        - extract_test: {jsonpath_mini: "0.id",  test: "exists"}
        - extract_test: {jsonpath_mini: "0.name",  test: "exists"}
   - extract_binds:
        - 'CURRENTID': {'jsonpath_mini': 'LAST.id'}
- test:
    - group: "Group"
    - name: "Update group"
    - url: "/rpc/v1/inventory.put-group.json"
    - method: "POST"
    - body: {template: "name=NewName&id=$CURRENTID"}
    - expected_status: [200]
    - headers: {template: {"Authorization": "$ACCESSTOKEN"}}
    - validators:
        - compare: {jsonpath_mini: "status",     comparator: "eq",     expected: 1}
```
There's a way to get the last entry of the array that the ``get-group`` method returns? Something to replace the ``LAST`` key on the tests.
