### ISSUE TITLE
How to validate REST response body fields?any example .yaml file to check?

### ISSUE THREAD

**Issue by ksreddy543** [svanoort/pyresttest#60]

**Comment by mariusmagureanu** [comment]
You can use validators, here you have an example:

```
- test:
    - group: "Demo"
    - name: "Some test name."
    - url: "your/request/url"
    - auth_username: "user"
    - auth_password: "pass"
    - method: "POST"
    - headers: {Content-Type: application/json}
    - body: {'template':'{"some_id":"123abc",  "other_data":"foo bar"}'}
    - expected_status: [400]
    - validators:
        - compare: {jsonpath_mini: 'Error', comparator: 'str_eq', expected: "your error message."}
```

In this example you'll validate that for the given POST request, the backend returns status code 400 and the following response body: ```{'Error':'your error message'}```


I'm not sure if this is what you were looking for, but you're welcome to provide more details of what your problem actually is.

**Comment by svanoort** [comment]
@mariusmagureanu Excellent answer!   The extractor name is 'header' and I have a sample below

```yaml
- test:
    - group: "Demo"
    - name: "Some test name."
    - url: "your/request/url"
    - auth_username: "user"
    - auth_password: "pass"
    - method: "POST"
    - headers: {Content-Type: application/json}
    - body: {'template':'{"some_id":"123abc",  "other_data":"foo bar"}'}
    - expected_status: [400]
    - validators:
        - compare: {extractor: 'Content-Type', comparator: 'str_eq', expected: "Application/json"}
```
