### ISSUE TITLE
Setting up Authorization for all tests in a file

### ISSUE THREAD

**Issue by Markionium** [svanoort/pyresttest#69]
Hello,

Just getting started, but thanks for what looks like a great tool! :)

When writing multiple tests against the same api that requires authorization. We are currently writing the following for each test. 

```yaml
 - auth_username: "admin"
 - auth_password: "district"
```

Is there a way we could specify that these settings are used for all the tests in that file?

```yaml
#Simple test file that simply does a GET on the base URL
---
- config: 
    - testset: "ME API" #Name test sets
- test: 
    - group: "api/me"
    - url: "/api/me" #Basic test to see if it is alive
    - auth_username: "admin"
    - auth_password: "district"
    - name: "End points exists"
    - expected_status: [200]
- test: 
    - group: "api/me"
    - url: "/api/me.json" #Basic validation test
    - auth_username: "admin"
    - auth_password: "district"
    - name: "Field validation should pass"
    - validators:
        - compare: {jsonpath_mini: "name",  comparator: "eq",  expected: 'John Traore'}
        - compare: {jsonpath_mini: "organisationUnits.0.name",  comparator: "eq",  expected: 'Sierra Leone'}
        - extract_test: {jsonpath_mini: "key_should_not_exist",  test: "not_exists"}
```
