### ISSUE TITLE
JMESPath Extractor - in progress under marklz

### ISSUE THREAD

**Issue by svanoort** [svanoort/pyresttest#78]
**What:**
As a pyresttest user who needs to do more detailed JSON analysis, I would like to be able to use full jsonpath support in working with request bodies (extraction for variables and content analysis).  This should be available if the library is installed and fail if not. 

**How:**
I would like to add a [jsonpath-rw](https://github.com/kennknowles/python-jsonpath-rw) extractor, set up to auto-register in the same way as the [jsonschema validator](https://github.com/svanoort/pyresttest/blob/master/pyresttest/ext/validator_jsonschema.py).  

It will also require adding [extending the autoload extensions](https://github.com/svanoort/pyresttest/blob/master/pyresttest/resttest.py#L675) to iterate through a list of extensions.  For now, that's sufficient but it might be desirable to try to autoload all of the 'ext' folder content.

This is an isolated task, easy enough for someone to execute as a PR.

**Comment by svanoort** [comment]
[JMESPath](http://jmespath.org/specification.html) may be a better option for some use cases, and supports returning the last element in an array, for example.

**Comment by marklz** [comment]
Sam - is it something and a junior-midlevel python coder can help you with?

**Comment by svanoort** [comment]
@marklz Absolutely!  It probably will not require much code to do the coupling, and all the aspects needed have documentation and examples (JSONschema extension, extensions.md for how to write an extension, and resttest.py loading of the jsonschema extension).  Fairly easy to throw together tests for this as well.

**Comment by marklz** [comment]
looked briefly at JMESPath ( https://github.com/jmespath/jmespath.py and the spec in the link above) - is it much more complex than this? I'm surely missing something...

```python
import jmespath

class JMESPathExtractor(AbstractExtractor):
    """ Extractor that uses JMESPath syntax
		See http://jmespath.org/specification.html for details
    """
    extractor_type = 'jmespath'
    is_body_extractor = True

    def extract_internal(self, query=None, args=None, body=None, headers=None):
        try:
            body = json.loads(body)
            return jmespath.search(query, body)
        except ValueError:
            raise ValueError("Not legal JSON!")

    @classmethod
    def parse(cls, config):
        base = JMESPathExtractor()
        return cls.configure_base(config, base)
        return base
```

**Comment by svanoort** [comment]
@marklz Nope, not much more complex than that for the core!  There's a couple more pieces to get it PR-ready, but not big ones.  First we need some basic unit tests (and I'm not sure here if JMESPath for python returns JSON text fragments or Python objects, but if  the first one, we need to call the json.loads function to parse them so the comparators work).  

Second, is an autoload for the extension [like we have for the jsonschema validator](https://github.com/svanoort/pyresttest/blob/master/pyresttest/resttest.py#L737).  So, less than a half-dozen lines of code, and there's already an example to work from.

Third:  an entry in the advanced_guide with the registered name & description, a syntax example, and a link to the JMESPath page (for more advanced uses).

Finally: I do apologize for the delay!  I've been sick with flu the last few days and only just got well enough to start looking at code again.

This looks like it would be a great addition to PyrestTest, and thank you!

**Comment by marklz** [comment]
No worry about reply times - I have a full time job too :-)
* Unit tests - I'm actually thinking to piggy back on JMESPath unit tests in https://github.com/jmespath/jmespath.py/tree/develop/tests/compliance; I can add code to test_validators.py that reads static texts as jmespath-compliance-1.json,  jmespath-compliance-2.json etc, and then do queries and check for results - all based on JMESPath tests.Does it make sense or is it too little or too much? 

* autoload - I see two options here:
Option 1 - add code to validators.py, and at the end of validators.py, next to similar statements add
```
register_extractor('jmespath', JMESPathExtractor.parse)
```
Option 2 - create a extractor_jmespath.py in ext/ folder, and at the end of that file add - not clear what. jsonschema has
```
EXTRACTORS = {'jmespath': JMESPathExtractor.parse}
```
and then in resttest.py add
```
try:
    import jmespath
    register_extensions('ext.extractor_jmespath')
except ImportError as ie:
    logging.debug(
        "Failed to load jmespath extractor, make sure the jmespath module is installed if you wish to use jmespath extractor.")
```
So, which way should I go?

* documentation - I'll do format of jsonpath_mini and contents of http://jmespath.org/tutorial.html, if it's ok with you

Mark.

**Comment by svanoort** [comment]
Ah, those full-time jobs! 

**Unit tests:**

I think that what you describe is more work than you really need.  Really we only need to exercise config parsing, basic query use, templating in the query, and error handling (including empty value returns).  As a nice-to-have, it would be helpful to have a test in a ComparatorValidator.

**Autoload:**

Option 2, please!  This way it's possible to successfully run PyRestTest without the Jmespath library installed, but if the library is present the extension is available.  And yes, the example you gave really is all you need there (the extension loader looks for registry variables) -- both snippets look correct to me at first glance.  

On consideration, it would be nice to convert the extension_use_test.sh to some form of functional test for autoloading extensions (that only runs if libraries are present)... but I'm certainly not making that a PR requirement since it's something I ought to have done a while back.

**Documentation:**

Ha!  It doesn't even need that much, just an example of syntax for using the extractor and what that returns, and a link to the tutorial there.

Hope that makes your life easier as you have a fulltime job too! ;-)

**Comment by marklz** [comment]
Can't register extension - what am I doing wrong?

{code}
[mzusman@pioneer-dev36 pyresttest]$ pyresttest http://172.17.230.6 aa.yaml --import_extensions 'ext.extractor_jmespath'
Traceback (most recent call last):
  File "/usr/bin/pyresttest", line 4, in <module>
    resttest.command_line_run(sys.argv[1:])
  File "/usr/lib/python2.6/site-packages/pyresttest/resttest.py", line 863, in command_line_run
    main(args)
  File "/usr/lib/python2.6/site-packages/pyresttest/resttest.py", line 769, in main
    register_extensions(extensions)
  File "/usr/lib/python2.6/site-packages/pyresttest/resttest.py", line 709, in register_extensions
    module = __import__(ext, globals(), locals(), package)
ImportError: No module named extractor_jmespath
[mzusman@pioneer-dev36 pyresttest]$ !ls
ls -ltr ext
total 20
-rw-rw-r-- 1 mzusman mzusman 1890 Nov 30 20:28 validator_jsonschema.py
-rw-rw-r-- 1 mzusman mzusman  126 Nov 30 20:28 __init__.py
-rw-rw-r-- 1 mzusman mzusman 1068 Dec  3 11:15 extractor_jmespath.py
-rw-rw-r-- 1 mzusman mzusman  296 Dec  3 11:41 __init__.pyc
-rw-rw-r-- 1 mzusman mzusman 1676 Dec  3 11:41 extractor_jmespath.pyc
{code}

**Comment by svanoort** [comment]
@marklz Simple, if it's using the --import_extensions argument, the path should be pyresttest.ext.extractor_jmespath, I believe -- it's relative to current folder.    If you're doing import like the jsonschema extractor, it's of course going to omit the first bit.

**Comment by marklz** [comment]
Good news - autoloader works all is well; I was running pyresttest - which was /usr/bin/pyrestest!
Once I started doing 
```
python resttest.py http://172.17.230.6 aa.yaml
```
we started to pick up correct code. Without any modifications, run my initial test - first two tests runn correctly, throws exception on 3rd one. I'll debug it tomorrow, but it's a nice progress
```
- test:
    - name: "correct url, correct authentication"
    - url: "/api/1.0/config/element/terminal/"
    - auth_username: "admin"
    - auth_password: "admin"
    - expected_status: [200]
    - validators:
        - compare: {jmespath: 'errors', comparator: 'count_eq', expected: 0 }
        - compare: {jmespath: 'meta.count', comparator: 'gt', expected: 0 }
        - compare: {jmespath: 'data.0.obj_attributes.mgmtsubnetmask', comparator: 'regex', expected: '255.255.255.*' }
```

**Comment by svanoort** [comment]
@marklz Excellent!

**Comment by marklz** [comment]
I'm going over http://jmespath.org/tutorial.html and it looks good so far:
* I've created a few simple input files
```
[mzusman@pioneer-dev36 pyresttest]$ for f in *; do echo ====== $f =====; cat $f; done
====== jmespath-test-1 =====
{"a": "foo", "b": "bar", "c": "baz"}
====== jmespath-test-2 =====
{"a": {"b": {"c": {"d": "value"}}}}
====== jmespath-test-3 =====
["a", "b", "c", "d", "e", "f"]
====== jmespath-test-4 =====
{"a": {
  "b": {
    "c": [
      {"d": [0, [1, 2]]},
      {"d": [3, 4]}
    ]
  }
}}
====== jmespath-test-5 =====
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
====== jmespath-test-6 =====
{
  "people": [
    {"first": "James", "last": "d"},
    {"first": "Jacob", "last": "e"},
    {"first": "Jayden", "last": "f"},
    {"missing": "different"}
  ],
  "foo": {"bar": "baz"}
}
```
* I have a test configuration
```
[mzusman@pioneer-dev36 pyresttest]$ cat aa.yaml
---
- config:
    - testset: "Basic tests"

- test:
    - name: "test-1"
    - url: "/jmespath-test-1"
    - expected_status: [200]
    - validators:
        - compare: {jmespath: 'a', comparator: 'eq', expected: 'foo' }
        - compare: {jmespath: 'b', comparator: 'eq', expected: 'bar' }
        - compare: {jmespath: 'c', comparator: 'eq', expected: 'baz' }

- test:
    - name: "test-2"
    - url: "/jmespath-test-2"
    - expected_status: [200]
    - validators:
        - compare: {jmespath: 'a.b.c.d', comparator: 'eq', expected: 'value' }

- test:
    - name: "test-3"
    - url: "/jmespath-test-3"
    - expected_status: [200]
    - validators:
        - compare: {jmespath: '[1]', comparator: 'eq', expected: 'b' }

- test:
    - name: "test-4"
    - url: "/jmespath-test-4"
    - expected_status: [200]
    - validators:
        - compare: {jmespath: 'a.b.c[0].d[1][0]', comparator: 'eq', expected: 1 }


- test:
    - name: "test-5"
    - url: "/jmespath-test-5"
    - expected_status: [200]
    - validators:
        - compare: {jmespath: 'length([0:5])', comparator: 'eq', expected: 5 }
        - compare: {jmespath: '[1:3]', comparator: 'eq', expected: '[1, 2]' }
        - compare: {jmespath: '[::2]', comparator: 'eq', expected: '[0, 2, 4, 6, 8]' }
        - compare: {jmespath: '[5:0:-1]', comparator: 'eq', expected: '[5, 4, 3, 2, 1]' }

- test:
    - name: "test-6"
    - url: "/jmespath-test-6"
    - expected_status: [200]
    - validators:
        - compare: {jmespath: 'people[*].first', comparator: 'eq', expected: "['James', 'Jacob', 'Jayden']" }
        - compare: {jmespath: 'people[:2].first', comparator: 'eq', expected: "['James', 'Jacob']" }

```
* everything passes
```
[mzusman@pioneer-dev36 pyresttest]$ python resttest.py http://pioneer-dev36.eng.idirect.net/~mzusman/pyresttest aa.yaml |& tee aa
1: jmespath : query = a  result = foo type = <type 'str'>
1: jmespath : query = b  result = bar type = <type 'str'>
1: jmespath : query = c  result = baz type = <type 'str'>
1: jmespath : query = a.b.c.d  result = value type = <type 'str'>
1: jmespath : query = [1]  result = b type = <type 'str'>
1: jmespath : query = a.b.c[0].d[1][0]  result = 1 type = <type 'int'>
1: jmespath : query = length([0:5])  result = 5 type = <type 'int'>
1: jmespath : query = [1:3]  result = [1, 2] type = <type 'list'>
1: jmespath : query = [::2]  result = [0, 2, 4, 6, 8] type = <type 'list'>
1: jmespath : query = [5:0:-1]  result = [5, 4, 3, 2, 1] type = <type 'list'>
1: jmespath : query = people[*].first  result = ['James', 'Jacob', 'Jayden'] type = <type 'list'>
1: jmespath : query = people[:2].first  result = ['James', 'Jacob'] type = <type 'list'>
Test Group Default SUCCEEDED: 6/6 Tests Passed!
```

I assume that for real unit tests, I'll have to convert URL requests to reading files - how do I handle from packaging POV? Put input files into ext? Into some other place?

Mark.
