### ISSUE TITLE
Unable to extract from response body

### ISSUE THREAD

**Issue by jbouzekri** [svanoort/pyresttest#99]
Hi,

Thanks for your awesome work.

I am trying to test the authentication/logout workflow of an API. When I login, it returns a token that I can use to logout.

This is my test file : 

```
---
- config:
    - testset: "Authentication feature"

- test:
    - name: "Unauthorized Access"
    - url: "/user/logout"
    - method: 'POST'
    - expected_status: [401]

- test:
    - name: "Authenticate"
    - url: "/user/login?mail=myemail&password=mypassword"
    - method: 'POST'
    - headers: {Content-Type: "application/json"}
    - extract_binds:
        - 'token': {'jsonpath_mini': 'response.token'}

- test:
    - name: "Logout"
    - url: "/user/logout?token=$token"
    - method: 'POST'
    - headers: {Authorization: "Bearer $token"}
```

As you can see in the last test, I tried to set $token in both the header and as a GET param. But it is never replaced by the value extracted from the previous tracker.

Please find bellow the body of the response when login : 

```
{
    "response": {
         "token": "aaaabbbbbccccddddeeee"
    },
    "success": 1
}
```

Thanks in advance

**Comment by svanoort** [comment]
Hi, I'm glad you're finding it useful, and thanks for reaching out with your question!

The reason you're seeing issues is that templating must be explicitly declared for elements (it is not done automatically, for a couple reasons). 

I've got a good example of this in the [content-test](https://github.com/svanoort/pyresttest/blob/master/pyresttest/content-test.yaml#L23).    So, for your case, the final test will look like: 

```yaml
- test:
    - name: "Logout"
    - url: "/user/logout?token=$token"
    - method: 'POST'
    - headers: {template: {Authorization: "Bearer $token"}}
```
One note: for headers, if you declare them as using a template, *all* values in the header map will be templated (header names and values), so if you're using $ signs in there, make sure to escape them with two $ signs (i.e. $$escaped).
